(cl:defpackage security_msgs-msg
  (:use )
  (:export
   "<CONFIRMTHREATACTION>"
   "CONFIRMTHREATACTION"
   "<CONFIRMTHREATACTIONFEEDBACK>"
   "CONFIRMTHREATACTIONFEEDBACK"
   "<CONFIRMTHREATACTIONGOAL>"
   "CONFIRMTHREATACTIONGOAL"
   "<CONFIRMTHREATACTIONRESULT>"
   "CONFIRMTHREATACTIONRESULT"
   "<CONFIRMTHREATFEEDBACK>"
   "CONFIRMTHREATFEEDBACK"
   "<CONFIRMTHREATGOAL>"
   "CONFIRMTHREATGOAL"
   "<CONFIRMTHREATRESULT>"
   "CONFIRMTHREATRESULT"
  ))

