; Auto-generated. Do not edit!


(cl:in-package security_msgs-msg)


;//! \htmlinclude ConfirmThreatFeedback.msg.html

(cl:defclass <ConfirmThreatFeedback> (roslisp-msg-protocol:ros-message)
  ((seconds_elapsed
    :reader seconds_elapsed
    :initarg :seconds_elapsed
    :type cl:integer
    :initform 0))
)

(cl:defclass ConfirmThreatFeedback (<ConfirmThreatFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConfirmThreatFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConfirmThreatFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name security_msgs-msg:<ConfirmThreatFeedback> is deprecated: use security_msgs-msg:ConfirmThreatFeedback instead.")))

(cl:ensure-generic-function 'seconds_elapsed-val :lambda-list '(m))
(cl:defmethod seconds_elapsed-val ((m <ConfirmThreatFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader security_msgs-msg:seconds_elapsed-val is deprecated.  Use security_msgs-msg:seconds_elapsed instead.")
  (seconds_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConfirmThreatFeedback>) ostream)
  "Serializes a message object of type '<ConfirmThreatFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'seconds_elapsed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConfirmThreatFeedback>) istream)
  "Deserializes a message object of type '<ConfirmThreatFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'seconds_elapsed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConfirmThreatFeedback>)))
  "Returns string type for a message object of type '<ConfirmThreatFeedback>"
  "security_msgs/ConfirmThreatFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConfirmThreatFeedback)))
  "Returns string type for a message object of type 'ConfirmThreatFeedback"
  "security_msgs/ConfirmThreatFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConfirmThreatFeedback>)))
  "Returns md5sum for a message object of type '<ConfirmThreatFeedback>"
  "dd91ab90b82cee8c3b5c35002eff35a1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConfirmThreatFeedback)))
  "Returns md5sum for a message object of type 'ConfirmThreatFeedback"
  "dd91ab90b82cee8c3b5c35002eff35a1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConfirmThreatFeedback>)))
  "Returns full string definition for message of type '<ConfirmThreatFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int32 seconds_elapsed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConfirmThreatFeedback)))
  "Returns full string definition for message of type 'ConfirmThreatFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int32 seconds_elapsed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConfirmThreatFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConfirmThreatFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ConfirmThreatFeedback
    (cl:cons ':seconds_elapsed (seconds_elapsed msg))
))
