; Auto-generated. Do not edit!


(cl:in-package security_msgs-msg)


;//! \htmlinclude ConfirmThreatGoal.msg.html

(cl:defclass <ConfirmThreatGoal> (roslisp-msg-protocol:ros-message)
  ((scan_seconds
    :reader scan_seconds
    :initarg :scan_seconds
    :type cl:integer
    :initform 0))
)

(cl:defclass ConfirmThreatGoal (<ConfirmThreatGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConfirmThreatGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConfirmThreatGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name security_msgs-msg:<ConfirmThreatGoal> is deprecated: use security_msgs-msg:ConfirmThreatGoal instead.")))

(cl:ensure-generic-function 'scan_seconds-val :lambda-list '(m))
(cl:defmethod scan_seconds-val ((m <ConfirmThreatGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader security_msgs-msg:scan_seconds-val is deprecated.  Use security_msgs-msg:scan_seconds instead.")
  (scan_seconds m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConfirmThreatGoal>) ostream)
  "Serializes a message object of type '<ConfirmThreatGoal>"
  (cl:let* ((signed (cl:slot-value msg 'scan_seconds)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConfirmThreatGoal>) istream)
  "Deserializes a message object of type '<ConfirmThreatGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'scan_seconds) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConfirmThreatGoal>)))
  "Returns string type for a message object of type '<ConfirmThreatGoal>"
  "security_msgs/ConfirmThreatGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConfirmThreatGoal)))
  "Returns string type for a message object of type 'ConfirmThreatGoal"
  "security_msgs/ConfirmThreatGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConfirmThreatGoal>)))
  "Returns md5sum for a message object of type '<ConfirmThreatGoal>"
  "2bc44bae5d0d3e24aa3ee601d14cc263")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConfirmThreatGoal)))
  "Returns md5sum for a message object of type 'ConfirmThreatGoal"
  "2bc44bae5d0d3e24aa3ee601d14cc263")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConfirmThreatGoal>)))
  "Returns full string definition for message of type '<ConfirmThreatGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 scan_seconds~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConfirmThreatGoal)))
  "Returns full string definition for message of type 'ConfirmThreatGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 scan_seconds~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConfirmThreatGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConfirmThreatGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ConfirmThreatGoal
    (cl:cons ':scan_seconds (scan_seconds msg))
))
