// Auto-generated. Do not edit!

// (in-package security_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ConfirmThreatResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.confirmed = null;
      this.reason = null;
    }
    else {
      if (initObj.hasOwnProperty('confirmed')) {
        this.confirmed = initObj.confirmed
      }
      else {
        this.confirmed = false;
      }
      if (initObj.hasOwnProperty('reason')) {
        this.reason = initObj.reason
      }
      else {
        this.reason = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ConfirmThreatResult
    // Serialize message field [confirmed]
    bufferOffset = _serializer.bool(obj.confirmed, buffer, bufferOffset);
    // Serialize message field [reason]
    bufferOffset = _serializer.string(obj.reason, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ConfirmThreatResult
    let len;
    let data = new ConfirmThreatResult(null);
    // Deserialize message field [confirmed]
    data.confirmed = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [reason]
    data.reason = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.reason);
    return length + 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'security_msgs/ConfirmThreatResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '338ce2e522f9ee6bad954bf83421f2fd';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    bool confirmed
    string reason
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ConfirmThreatResult(null);
    if (msg.confirmed !== undefined) {
      resolved.confirmed = msg.confirmed;
    }
    else {
      resolved.confirmed = false
    }

    if (msg.reason !== undefined) {
      resolved.reason = msg.reason;
    }
    else {
      resolved.reason = ''
    }

    return resolved;
    }
};

module.exports = ConfirmThreatResult;
