// Generated by gencpp from file security_msgs/ConfirmThreatResult.msg
// DO NOT EDIT!


#ifndef SECURITY_MSGS_MESSAGE_CONFIRMTHREATRESULT_H
#define SECURITY_MSGS_MESSAGE_CONFIRMTHREATRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace security_msgs
{
template <class ContainerAllocator>
struct ConfirmThreatResult_
{
  typedef ConfirmThreatResult_<ContainerAllocator> Type;

  ConfirmThreatResult_()
    : confirmed(false)
    , reason()  {
    }
  ConfirmThreatResult_(const ContainerAllocator& _alloc)
    : confirmed(false)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _confirmed_type;
  _confirmed_type confirmed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;





  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> const> ConstPtr;

}; // struct ConfirmThreatResult_

typedef ::security_msgs::ConfirmThreatResult_<std::allocator<void> > ConfirmThreatResult;

typedef boost::shared_ptr< ::security_msgs::ConfirmThreatResult > ConfirmThreatResultPtr;
typedef boost::shared_ptr< ::security_msgs::ConfirmThreatResult const> ConfirmThreatResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::security_msgs::ConfirmThreatResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::security_msgs::ConfirmThreatResult_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatResult_<ContainerAllocator2> & rhs)
{
  return lhs.confirmed == rhs.confirmed &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::security_msgs::ConfirmThreatResult_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace security_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "338ce2e522f9ee6bad954bf83421f2fd";
  }

  static const char* value(const ::security_msgs::ConfirmThreatResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x338ce2e522f9ee6bULL;
  static const uint64_t static_value2 = 0xad954bf83421f2fdULL;
};

template<class ContainerAllocator>
struct DataType< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "security_msgs/ConfirmThreatResult";
  }

  static const char* value(const ::security_msgs::ConfirmThreatResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool confirmed\n"
"string reason\n"
;
  }

  static const char* value(const ::security_msgs::ConfirmThreatResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirmed);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfirmThreatResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::security_msgs::ConfirmThreatResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::security_msgs::ConfirmThreatResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "confirmed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirmed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECURITY_MSGS_MESSAGE_CONFIRMTHREATRESULT_H
