// Generated by gencpp from file security_msgs/ConfirmThreatActionGoal.msg
// DO NOT EDIT!


#ifndef SECURITY_MSGS_MESSAGE_CONFIRMTHREATACTIONGOAL_H
#define SECURITY_MSGS_MESSAGE_CONFIRMTHREATACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <security_msgs/ConfirmThreatGoal.h>

namespace security_msgs
{
template <class ContainerAllocator>
struct ConfirmThreatActionGoal_
{
  typedef ConfirmThreatActionGoal_<ContainerAllocator> Type;

  ConfirmThreatActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ConfirmThreatActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::security_msgs::ConfirmThreatGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ConfirmThreatActionGoal_

typedef ::security_msgs::ConfirmThreatActionGoal_<std::allocator<void> > ConfirmThreatActionGoal;

typedef boost::shared_ptr< ::security_msgs::ConfirmThreatActionGoal > ConfirmThreatActionGoalPtr;
typedef boost::shared_ptr< ::security_msgs::ConfirmThreatActionGoal const> ConfirmThreatActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace security_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d9a0f5b6aa7287600aa9cb03c7d29cf";
  }

  static const char* value(const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d9a0f5b6aa72876ULL;
  static const uint64_t static_value2 = 0x00aa9cb03c7d29cfULL;
};

template<class ContainerAllocator>
struct DataType< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "security_msgs/ConfirmThreatActionGoal";
  }

  static const char* value(const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ConfirmThreatGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: security_msgs/ConfirmThreatGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 scan_seconds\n"
;
  }

  static const char* value(const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfirmThreatActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::security_msgs::ConfirmThreatActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECURITY_MSGS_MESSAGE_CONFIRMTHREATACTIONGOAL_H
