// Generated by gencpp from file security_msgs/ConfirmThreatGoal.msg
// DO NOT EDIT!


#ifndef SECURITY_MSGS_MESSAGE_CONFIRMTHREATGOAL_H
#define SECURITY_MSGS_MESSAGE_CONFIRMTHREATGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace security_msgs
{
template <class ContainerAllocator>
struct ConfirmThreatGoal_
{
  typedef ConfirmThreatGoal_<ContainerAllocator> Type;

  ConfirmThreatGoal_()
    : scan_seconds(0)  {
    }
  ConfirmThreatGoal_(const ContainerAllocator& _alloc)
    : scan_seconds(0)  {
  (void)_alloc;
    }



   typedef int32_t _scan_seconds_type;
  _scan_seconds_type scan_seconds;





  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ConfirmThreatGoal_

typedef ::security_msgs::ConfirmThreatGoal_<std::allocator<void> > ConfirmThreatGoal;

typedef boost::shared_ptr< ::security_msgs::ConfirmThreatGoal > ConfirmThreatGoalPtr;
typedef boost::shared_ptr< ::security_msgs::ConfirmThreatGoal const> ConfirmThreatGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator2> & rhs)
{
  return lhs.scan_seconds == rhs.scan_seconds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace security_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bc44bae5d0d3e24aa3ee601d14cc263";
  }

  static const char* value(const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bc44bae5d0d3e24ULL;
  static const uint64_t static_value2 = 0xaa3ee601d14cc263ULL;
};

template<class ContainerAllocator>
struct DataType< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "security_msgs/ConfirmThreatGoal";
  }

  static const char* value(const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 scan_seconds\n"
;
  }

  static const char* value(const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scan_seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfirmThreatGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::security_msgs::ConfirmThreatGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::security_msgs::ConfirmThreatGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "scan_seconds: ";
    Printer<int32_t>::stream(s, indent + "  ", v.scan_seconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECURITY_MSGS_MESSAGE_CONFIRMTHREATGOAL_H
