// Generated by gencpp from file security_msgs/ConfirmThreatFeedback.msg
// DO NOT EDIT!


#ifndef SECURITY_MSGS_MESSAGE_CONFIRMTHREATFEEDBACK_H
#define SECURITY_MSGS_MESSAGE_CONFIRMTHREATFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace security_msgs
{
template <class ContainerAllocator>
struct ConfirmThreatFeedback_
{
  typedef ConfirmThreatFeedback_<ContainerAllocator> Type;

  ConfirmThreatFeedback_()
    : seconds_elapsed(0)  {
    }
  ConfirmThreatFeedback_(const ContainerAllocator& _alloc)
    : seconds_elapsed(0)  {
  (void)_alloc;
    }



   typedef int32_t _seconds_elapsed_type;
  _seconds_elapsed_type seconds_elapsed;





  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ConfirmThreatFeedback_

typedef ::security_msgs::ConfirmThreatFeedback_<std::allocator<void> > ConfirmThreatFeedback;

typedef boost::shared_ptr< ::security_msgs::ConfirmThreatFeedback > ConfirmThreatFeedbackPtr;
typedef boost::shared_ptr< ::security_msgs::ConfirmThreatFeedback const> ConfirmThreatFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.seconds_elapsed == rhs.seconds_elapsed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator1> & lhs, const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace security_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd91ab90b82cee8c3b5c35002eff35a1";
  }

  static const char* value(const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd91ab90b82cee8cULL;
  static const uint64_t static_value2 = 0x3b5c35002eff35a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "security_msgs/ConfirmThreatFeedback";
  }

  static const char* value(const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int32 seconds_elapsed\n"
"\n"
;
  }

  static const char* value(const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seconds_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfirmThreatFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::security_msgs::ConfirmThreatFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "seconds_elapsed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.seconds_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECURITY_MSGS_MESSAGE_CONFIRMTHREATFEEDBACK_H
